# Generated by Django 5.2.7 on 2025-10-07 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_pods', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GardenEnvironmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ph_level', models.FloatField(blank=True, null=True)),
                ('ec_level', models.FloatField(blank=True, null=True)),
                ('water_temp_c', models.FloatField(blank=True, null=True)),
                ('dissolved_oxygen', models.FloatField(blank=True, null=True)),
                ('air_temp_c', models.FloatField(blank=True, null=True)),
                ('humidity_percent', models.FloatField(blank=True, null=True)),
                ('light_intensity_lux', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_logs', to='garden.garden')),
            ],
        ),
        migrations.CreateModel(
            name='GardenPod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Empty'), (1, 'Planted'), (2, 'Growing'), (3, 'Harvesting'), (4, 'Maintenance')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='garden.garden')),
            ],
        ),
    ]
